name: buddies
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  grouped_buttons: ^1.0.4

  image_picker: ^0.6.7+11

  google_sign_in: ^4.5.4
  flutter_facebook_auth: ^0.3.1+1
  flutter_facebook_login: ^3.0.0
  flutter_launcher_icons: ^0.8.0
  fluttertoast: ^7.1.1
  country_code_picker: ^1.5.0
  firebase_auth: ^0.16.1
 # cloud_firestore: ^0.13.6
  cloud_firestore: ^0.13.6
  firebase_core: ^0.4.0+9
  #cupertino_icons: ^0.1.2
  bubble_tab_indicator: ^0.1.3
  cached_network_image: ^0.5.0+1
  page_indicator: ^0.1.0
  page_view_indicator: ^0.3.0+1
  flutter_masked_text:
  font_awesome_flutter: ^8.2.0
  #swipable: ^0.1.0
  fluttery_dart2: ^0.0.9

  swipedetector: ^1.2.0
    #fluttery:
  flutter_swiper: ^1.1.4





  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/logo.png
    - lib/images/bg1.png
    - lib/images/Button.png
    - lib/images/buddies.png
    - lib/images/bg3.png
    - lib/images/PlusIcon.png
    - lib/images/gallery.png
    - lib/images/camera.png
    - assets/images/app_icon.png
    - assets/images/ava6.png
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/hookup.png
    - assets/images/swipe.png
    - assets/images/match.png
    - assets/images/avatar.jpg
    - assets/images/chat2.png
    - assets/images/ic_chat.png
    - assets/images/hookup_icon.png
    - assets/images/hookup_icon_small.png
    - assets/images/lightening.png
    - lib/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:


  android: "launcher_icon"
  ios: true
  image_path: "lib/images/icon.png"
